package protogen.test.resource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.ModelAttribute;

import edu.uiowa.icts.spring.Security;
import protogen.test.controller.AbstractSecondschemaController;

/**
 * Generated by Protogen
 * @since 06/26/2015 16:01:38 CDT
 */
public abstract class AbstractSecondschemaResource extends AbstractSecondschemaController {


}