package edu.uiowa.icts.protogen.springhibernate.velocity;

import static org.junit.Assert.*;
import static org.hamcrest.Matchers.*;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;

import org.junit.Test;

import edu.uiowa.webapp.Schema;

public class AbstractControllerMVCTestsGeneratorTest {

	@Test
	public void shouldGenerateJavaSourceCodeForAbstractSpringMVCTestFile() {
		String packageName = "edu.uiowa.icts";

		Schema schema = new Schema();
		schema.setSqlLabel( "ictssysadmin" );
		schema.setUid( "ictssysadmin-uid" );
		schema.setLabel( "ictssysadmin" );

		AbstractControllerMVCTestsGenerator generator = new AbstractControllerMVCTestsGenerator( schema, packageName, new Properties() );
		String sourceCode = generator.javaSourceCode();

		assertThat( sourceCode, containsString( "package edu.uiowa.icts.ictssysadmin.controller;" ) );
		assertThat( sourceCode, containsString( "* Generated by Protogen" ) );

		SimpleDateFormat ft = new SimpleDateFormat( "EEE MMM dd" );
		assertThat( sourceCode, containsString( ft.format( new Date() ) ) );

	}

}
