package ${packageName};

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.springframework.http.*;
import org.springframework.web.bind.annotation.ExceptionHandler;

import edu.uiowa.icts.exception.EntityNotFoundException;
import ${abstractResourcePackageName}.${abstractResourceClassName};

/**
 * Generated by Protogen
 * @since ${date}
 */
public abstract class ${abstractApiResourceClassName} extends ${abstractResourceClassName} {

	@ExceptionHandler( value = EntityNotFoundException.class )	
	public ResponseEntity<Map<String, Object>> mappingNotFound( HttpServletRequest request ) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put( "message", request.getRequestURI() + " could not be found." );
		return new ResponseEntity<Map<String, Object>>( map, HttpStatus.NOT_FOUND );
	}
	
	@ExceptionHandler( value = Exception.class )
	public ResponseEntity<Map<String, Object>> handleException( Exception exception ) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put( "message", exception.getMessage() );
		return new ResponseEntity<Map<String, Object>>( map, HttpStatus.INTERNAL_SERVER_ERROR );
	}

	
}