package ${packageName};

import java.util.HashMap;
import java.util.Map;

import org.springframework.http.*;
import org.springframework.web.bind.annotation.ExceptionHandler;

import ${controllerPackageName}.${abstractControllerClassName};

/**
 * Generated by Protogen
 * @since ${date}
 */
public abstract class ${abstractResourceClassName} extends ${abstractControllerClassName} {

	@ExceptionHandler( value = Exception.class )
	public ResponseEntity<Map<String, Object>> handleException( Exception exception ) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put( "error", true );
		map.put( "message", exception.getMessage() );
		return new ResponseEntity<Map<String, Object>>( map, HttpStatus.INTERNAL_SERVER_ERROR );
	}

}