package ${packageName};

#*
 * %L
 * Protogen
 * %%
 * Copyright (C) 2009 - 2015 University of Iowa Institute for Clinical and Translational Science (ICTS)
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * L%
 *#

import java.util.HashMap;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.ExceptionHandler;
import ${daoPackageName}.${daoServiceClassName};
import edu.uiowa.icts.spring.Security;

/**
 * Generated by Protogen
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since ${date}
 */
public abstract class ${abstractResourceClassName} {

	@Autowired
	protected ${daoServiceClassName} ${daoServiceVariableName};

	@ModelAttribute( value = "username" )
	public String getUsername() {
		if ( Security.isAuthenticated() ) {
			return SecurityContextHolder.getContext().getAuthentication().getName();
		}
		return null;
	}

}